firstName = input("What is your first name? ")
lastName = input("What is your last name? ")
location= input("What is your location? ")
age = input("What is your age? ")
print("hi " + firstName + lastName + "! Your location is in" + location + "and you are " + age + "years old.")